[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<arduino_mega/main.cpp>
lib_deps = 
    adafruit/Adafruit GFX Library
    prenticedavid/MCUFRIEND_kbv
    adafruit/Adafruit TouchScreen

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<arduino_mega/main.cpp>
lib_deps = 
    adafruit/Adafruit GFX Library
    prenticedavid/MCUFRIEND_kbv
    adafruit/Adafruit TouchScreen

[env:m5stack-coreink]
platform = espressif32
board = m5stack-coreink
framework = arduino
lib_ldf_mode = deep
build_src_filter = +<m5_core_ink/main_coreink.cpp>
upload_speed = 115200
upload_port = COM4
lib_deps = 
    m5stack/M5Core-Ink
    m5stack/M5GFX
