[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    adafruit/Adafruit GFX Library
    prenticedavid/MCUFRIEND_kbv
    adafruit/Adafruit TouchScreen

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
    adafruit/Adafruit GFX Library
    prenticedavid/MCUFRIEND_kbv
    adafruit/Adafruit TouchScreen

[env:test_simulator]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_protocol = custom
upload_command = echo Uploading to simulator... > $SOURCE
lib_deps = 
    adafruit/Adafruit GFX Library
    prenticedavid/MCUFRIEND_kbv
    adafruit/Adafruit TouchScreen
